services:
  postgres:
    image: postgres:17.2
    container_name: db-container
    env_file: ".env"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
      - ./mock_data:/mock_data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres:
    driver: local

  